name: Keep Backend and Frontend Alive

on:
  schedule:
    - cron: "*/3 * * * *"  # Ejecuta la acción cada 3 minutos

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send a request to keep the backend alive
        run: curl -I https://s18-23-n-java-react.onrender.com/swagger-ui/index.html#/

      - name: Send a request to keep the frontend alive
        run: curl -I https://rentify-desarrollo.onrender.com/
